_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.11.5
        t:
            "1":
                - 2
                - 3
                - 12
                - 55
            "2":
                - 2
                - 3
                - 12
                - 55
            "3":
                - 2
                - 3
                - 8
                - 23
                - 55
            "4": 3.11.5
            "5": 0.18.5
            "8":
                - 1
                - 3
                - 5
            "10":
                - 9
                - 17
            "12": 0.18.5
            "13": windows-amd64
